Add CI check for uncommitted docs changes
Signed-off-by: Timo Sand <timo.sand@f-secure.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -26,6 +26,14 @@ jobs:
       - run: make tools
       - run: make lint
       - run: make docs-lint
+
+      - name: Check for uncommitted docs changes
+        run: |
+          tfplugindocs generate
+          if ![[ -z $(git status --porcelain) ]]; then
+            echo "::error::Uncommitted changes after tfplugindocs generate"
+            exit 1
+          fi
       - run: make build
       - run: make test
 
